"use client";

import { useEffect, useMemo, useState } from "react";

type Profile = { slug:string; nome:string; categorias:string[]; localidades:string[]; resumo:string; preco_desde?:string; cover_image?:string; foto_fonte?:string; fotos?:string[]; website?:string; instagram?:string; facebook?:string; whatsapp?:string; fonte?:string; content_html?:string; status:string; tipo_perfil:string };
type Candidate = { id:string; url:string; nome?:string; descricao?:string; imagem?:string; categoria_sugerida?:string; localidade_sugerida?:string; estado:string };

const empty = { nome:"", slug:"", categorias:"", localidades:"", precoDesde:"", resumo:"", contentHtml:"", coverImage:"", fotoFonte:"", fotos:"", website:"", instagram:"", facebook:"", whatsapp:"", fonte:"", status:"published", tipoPerfil:"diretorio" };

export default function AdminPage(){
  const [profiles,setProfiles]=useState<Profile[]>([]); const [candidates,setCandidates]=useState<Candidate[]>([]); const [form,setForm]=useState<any>(empty); const [editing,setEditing]=useState<string|null>(null); const [tab,setTab]=useState<"profiles"|"candidates">("profiles"); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
  async function load(){ setLoading(true); const [p,c]=await Promise.all([fetch("/api/admin/professionals"),fetch("/api/admin/candidates")]); const pj=await p.json(); const cj=await c.json(); if(!p.ok) setMessage(pj.error||"Erro"); else setProfiles(pj); if(c.ok) setCandidates(cj); setLoading(false); }
  useEffect(()=>{load()},[]);
  const published=useMemo(()=>profiles.filter(p=>p.status==="published").length,[profiles]);
  function set(k:string,v:string){setForm((x:any)=>({...x,[k]:v}))}
  function edit(p:Profile){setEditing(p.slug);setForm({nome:p.nome,slug:p.slug,categorias:p.categorias?.join("\n")||"",localidades:p.localidades?.join("\n")||"",precoDesde:p.preco_desde||"",resumo:p.resumo||"",contentHtml:p.content_html||"",coverImage:p.cover_image||"",fotoFonte:p.foto_fonte||"",fotos:p.fotos?.join("\n")||"",website:p.website||"",instagram:p.instagram||"",facebook:p.facebook||"",whatsapp:p.whatsapp||"",fonte:p.fonte||"",status:p.status,tipoPerfil:p.tipo_perfil||"diretorio"}); window.scrollTo({top:0,behavior:"smooth"})}
  function clear(){setEditing(null);setForm(empty)}
  async function save(e:React.FormEvent){e.preventDefault();setMessage("A guardar…"); const payload={...form,categorias:form.categorias.split(/\n|,/).map((x:string)=>x.trim()).filter(Boolean),localidades:form.localidades.split(/\n|,/).map((x:string)=>x.trim()).filter(Boolean),fotos:form.fotos.split(/\n/).map((x:string)=>x.trim()).filter(Boolean)}; const r=await fetch(editing?`/api/admin/professionals/${encodeURIComponent(editing)}`:"/api/admin/professionals",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const j=await r.json(); if(!r.ok){setMessage(j.error||"Erro ao guardar");return} setMessage("Guardado."); clear(); await load()}
  async function remove(slug:string){if(!confirm("Arquivar este perfil?"))return; const r=await fetch(`/api/admin/professionals/${encodeURIComponent(slug)}`,{method:"DELETE"}); if(r.ok){setMessage("Perfil removido.");await load()}else setMessage("Não foi possível remover.")}
  async function importCandidate(c:Candidate){ setTab("profiles"); setForm({...empty,nome:c.nome||"",resumo:c.descricao||"",coverImage:c.imagem||"",website:c.url||"",fonte:c.url||"",categorias:c.categoria_sugerida||"",localidades:c.localidade_sugerida||""}); setEditing(null); await fetch(`/api/admin/candidates/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({estado:"revisto"})}); setMessage("Candidato carregado no formulário. Revê e publica.") }
  async function reject(c:Candidate){await fetch(`/api/admin/candidates/${c.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({estado:"rejeitado"})});await load()}
  return <main className="min-h-screen bg-canvas px-6 py-10"><div className="mx-auto max-w-6xl">
    <div className="flex flex-col justify-between gap-4 border-b border-black/10 pb-6 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-widest text-violet">Yuppi CMS</p><h1 className="mt-2 font-display text-4xl text-ink">Gerir diretório</h1><p className="mt-2 text-inkSoft">{published} perfis publicados · {candidates.filter(c=>c.estado==="novo").length} candidatos novos</p></div><button onClick={clear} className="rounded-full bg-violet px-5 py-3 text-sm font-semibold text-white">+ Novo profissional</button></div>
    {message&&<div className="mt-5 rounded-xl bg-violet-light px-4 py-3 text-sm text-ink">{message}</div>}
    <div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
      <section className="rounded-xl2 bg-white p-6 shadow-card"><div className="mb-4 flex items-center justify-between"><p className="text-sm text-inkSoft">Perfis publicados ficam online sem novo deploy.</p><label className="cursor-pointer rounded-full border border-black/10 px-4 py-2 text-xs font-semibold text-ink">Importar candidatos JSON<input type="file" accept="application/json" className="hidden" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const arr=JSON.parse(await file.text());for(const c of arr){await fetch("/api/admin/candidates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(c)})}setMessage(`Importados ${arr.length} candidatos.`);await load()}catch{setMessage("JSON inválido.")}}}/></label></div><div className="flex gap-2 border-b border-black/10 pb-4"><button onClick={()=>setTab("profiles")} className={`rounded-full px-4 py-2 text-sm ${tab==="profiles"?"bg-violet text-white":"bg-canvasSoft text-ink"}`}>Profissionais</button><button onClick={()=>setTab("candidates")} className={`rounded-full px-4 py-2 text-sm ${tab==="candidates"?"bg-violet text-white":"bg-canvasSoft text-ink"}`}>Candidatos</button></div>
      {tab==="profiles"?<div className="mt-5 space-y-3">{loading?<p>A carregar…</p>:profiles.map(p=><div key={p.slug} className="flex items-center gap-4 rounded-xl border border-black/10 p-3"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-lg bg-canvasSoft">{p.cover_image&&<img src={p.cover_image} alt="" className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><p className="font-semibold text-ink">{p.nome}</p><p className="truncate text-xs text-inkSoft">{p.categorias?.join(" · ")} · {p.localidades?.join(" · ")}</p><p className="text-xs text-inkSoft">{p.status}</p></div><button onClick={()=>edit(p)} className="text-sm font-semibold text-violet">Editar</button><button onClick={()=>remove(p.slug)} className="text-sm text-inkSoft">Arquivar</button></div>)}</div>:<div className="mt-5 space-y-3">{candidates.length===0?<p className="text-inkSoft">Ainda não há candidatos. Corre o scraper e importa os resultados.</p>:candidates.map(c=><div key={c.id} className="rounded-xl border border-black/10 p-4"><p className="font-semibold text-ink">{c.nome||c.url}</p><p className="mt-1 break-all text-xs text-inkSoft">{c.url}</p><p className="mt-1 text-sm text-inkSoft">{c.descricao||"Sem descrição."}</p><div className="mt-3 flex gap-3"><button onClick={()=>importCandidate(c)} className="rounded-full bg-violet px-4 py-2 text-xs font-semibold text-white">Rever e importar</button><button onClick={()=>reject(c)} className="rounded-full border border-black/10 px-4 py-2 text-xs">Rejeitar</button></div></div>)}</div>}
      </section>
      <form onSubmit={save} className="rounded-xl2 bg-white p-6 shadow-card"><div className="flex items-center justify-between"><h2 className="font-display text-2xl text-ink">{editing?"Editar perfil":"Novo perfil"}</h2>{editing&&<button type="button" onClick={clear} className="text-sm text-inkSoft">Cancelar</button>}</div><div className="mt-5 grid gap-4"><Field label="Nome" value={form.nome} onChange={(v:string)=>set("nome",v)} required/><Field label="Slug (opcional)" value={form.slug} onChange={(v:string)=>set("slug",v)}/><Field label="Categorias (uma por linha)" value={form.categorias} onChange={(v:string)=>set("categorias",v)}/><Field label="Localidades (uma por linha)" value={form.localidades} onChange={(v:string)=>set("localidades",v)}/><Field label="Resumo" value={form.resumo} onChange={(v:string)=>set("resumo",v)} textarea/><Field label="Conteúdo HTML (opcional)" value={form.contentHtml} onChange={(v:string)=>set("contentHtml",v)} textarea/><Field label="Foto principal — URL" value={form.coverImage} onChange={(v:string)=>set("coverImage",v)}/><Field label="Fonte da foto — URL" value={form.fotoFonte} onChange={(v:string)=>set("fotoFonte",v)}/><Field label="Fotos adicionais — URLs, uma por linha" value={form.fotos} onChange={(v:string)=>set("fotos",v)}/><Field label="Website" value={form.website} onChange={(v:string)=>set("website",v)}/><Field label="Instagram" value={form.instagram} onChange={(v:string)=>set("instagram",v)}/><Field label="Facebook" value={form.facebook} onChange={(v:string)=>set("facebook",v)}/><Field label="WhatsApp" value={form.whatsapp} onChange={(v:string)=>set("whatsapp",v)}/><Field label="Fonte / página de referência" value={form.fonte} onChange={(v:string)=>set("fonte",v)}/><div className="grid grid-cols-2 gap-3"><Select label="Estado" value={form.status} onChange={(v:string)=>set("status",v)} options={[["published","Publicado"],["draft","Rascunho"],["archived","Arquivado"]]}/><Select label="Tipo" value={form.tipoPerfil} onChange={(v:string)=>set("tipoPerfil",v)} options={[["diretorio","Diretório"],["parceiro","Parceiro"]]}/></div><button className="mt-2 rounded-full bg-violet px-6 py-3.5 text-sm font-semibold text-white">{editing?"Guardar alterações":"Publicar profissional"}</button></div></form>
    </div>
    <div className="mt-8 rounded-xl2 bg-violet-light p-6 text-sm text-ink"><strong>Como funciona:</strong> o site público lê os perfis publicados da base de dados. Podes mudar fotos, links, categorias e textos aqui sem novo deploy. O scraper só cria candidatos; tu decides o que entra no diretório.</div>
  </div></main>
}
function Field({label,value,onChange,textarea=false,required=false}:{label:string;value:string;onChange:(v:string)=>void;textarea?:boolean;required?:boolean}){return <label className="block text-sm font-medium text-ink">{label}{textarea?<textarea required={required} value={value} onChange={e=>onChange(e.target.value)} rows={4} className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-2.5 font-normal outline-none focus:border-violet"/>:<input required={required} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-2.5 font-normal outline-none focus:border-violet"/>}</label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="block text-sm font-medium text-ink">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-black/10 px-3 py-2.5 font-normal">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
